name: Release please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
          include-component-in-tag: true
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - if: ${{ steps.release.outputs['dockerfile--release_created'] }}
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}[bot]@users.noreply.github.com'
          git tag -d v${{ steps.release.outputs['dockerfile--major'] }} || true
          git tag -d v${{ steps.release.outputs['dockerfile--major'] }}.${{ steps.release.outputs['dockerfile--minor'] }} || true
          git push origin :v${{ steps.release.outputs['dockerfile--major'] }} || true
          git push origin :v${{ steps.release.outputs['dockerfile--major'] }}.${{ steps.release.outputs['dockerfile--minor'] }} || true

          git tag -a v${{ steps.release.outputs['dockerfile--major'] }} -m "Release v${{ steps.release.outputs['dockerfile--major'] }}"
          git tag -a v${{ steps.release.outputs['dockerfile--major'] }}.${{ steps.release.outputs['dockerfile--minor'] }} -m "Release v${{ steps.release.outputs['dockerfile--major'] }}.${{ steps.release.outputs['dockerfile--minor'] }}"
          git push origin v${{ steps.release.outputs['dockerfile--major'] }}
          git push origin v${{ steps.release.outputs['dockerfile--major'] }}.${{ steps.release.outputs['dockerfile--minor'] }}
